version: "3.5"
services:
  angular-service:
    image: docker-angular-image
    container_name: docker-angular-container
    build: ./
    volumes:
      - './usr/src/app'
    ports:
      - '4200:4200'
    environment:
      NODE_ENV: Development
